Repository wecode-bootcamp-korea/fullstack1-2nd-SKYROCKET-backend, pull requests merged in 2021-08, with the labels that each got.

#6 [감하영] 모델링 수정 (서브 카테고리 테이블 삭제 및 user의 email에 unique 속성 추가)
  prisma/migrations/20210802030354_deleted_sub_category_model/migration.sql
  prisma/migrations/20210802030424_added_english_name_in_category_model/migration.sql
  prisma/migrations/20210802031611_added_email_unique_identifiers_in_user_model/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#8 [감하영] 프로젝트 상태(statuses) 테이블 추가로 인한 모델링 수정
  prisma/migrations/20210803031856_added_status_model/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#9 [박미정] 프리즈마 모델링 수정 - 유저 테이블컬럼 널러블하게 수정
  prisma/migrations/20210803234357_modified_user_model/migration.sql
  prisma/schema.prisma
Labels: Status: Accepted

#4 [박미정] 일반 로그인/회원가입/미들웨어 구현 완료, 회원가입, 로그인 유닛테스트 완료
  .babelrc
  .gitignore
  app.js
  controllers/UserController.js
  controllers/index.js
  middlewares/validateToken.js
  models/UserDao.js
  models/index.js
  package-lock.json
  package.json
  routes/UserRouter.js
  routes/index.js
  services/UserService.js
  services/index.js
  test/data/user.js
  test/user.test.js
Labels: Status: 수정 요청

#10 [박미정] 카카오 로그인, 회원가입완료, 레이어드 패턴으로 수정 완료
  app.js
  controllers/KakaoController.js
  controllers/index.js
  models/KakaoDao.js
  models/index.js
  package-lock.json
  prisma/migrations/20210802184221_/migration.sql
  routes/KakaoRouter.js
  routes/index.js
  services/KakaoService.js
  services/index.js
Labels: Status: 수정 요청

#5 [감하영] 상품 리스트 API (전체 상품, 쿼리 스트링을 이용한 필터링) 구현 & errorGenerator 생성 & 유닛 테스트 구현
  controllers/ProjectController.js
  controllers/index.js
  models/ProjectDao.js
  models/index.js
  package.json
  routes/ProjectRouter.js
  routes/index.js
  services/ProjectService.js
  services/index.js
  test/data/project.js
  test/project.test.js
  utils/errorGenerator.js
Labels: Status: Accepted

#12 Add: Category, Status API 및 유닛 테스트 구현
  controllers/ProjectController.js
  models/ProjectDao.js
  routes/ProjectRouter.js
  services/ProjectService.js
  test/project.test.js
Labels: Status: 질문, Status: Accepted

#13 [박미정]디테일API 구현중
  controllers/ProjectController.js
  models/ProjectDao.js
  routes/ProjectRouter.js
  services/ProjectService.js
Labels: Status: 추가 기능 구현 중, Status: Accepted
